#
# To just build the module, use:
#     make M=drivers/devcon
#

devcon-y := \
	charset.o \
	input.o \
	keyboard.o \
	main.o \
	page.o \
	parser.o \
	screen.o \
	terminal.o \
	tty.o \
	video.o \
	wcwidth.o

obj-$(CONFIG_DEVCON) += devcon.o
